/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 26-Aug-2018 00:46:44
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * G:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 7
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,2,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.9882628229406,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.9703742185294,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.9816878983702,                 0,                 0 
  },
  {
                   1,                -1,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,2,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.975837893728,   0.9772133980349 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.940073133948,   0.9414237401697 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.9633757967404,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
